Cherry pick of e1a2c8dd82e8131c416b1ec6349aaaf42b604276 failed
stdout:

stderr:
12:12:06.228972 git.c:344               trace: built-in: git cherry-pick e1a2c8dd82e8131c416b1ec6349aaaf42b604276
error: could not apply e1a2c8dd82e... [FIX] website, *: fix elements position in fullscreen or/and edit mode
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: